# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test lib

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches: [main]
    paths:
      - "lib/**"
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    name: test-lib
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Corepack enable
        run: corepack enable && yarn set version 4.0.2
      - name: Use Node.js 18x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "lib/yarn.lock"
      - name: Cache jest results
        uses: actions/cache@v3
        with:
          path: ~/.jest-cache
          key: jest-cache
      - name: Build Flagright Lib
        run: corepack enable && yarn set version 4.0.2 && yarn install --immutable
        working-directory: "lib"
      - run: yarn run tsc:ci
        working-directory: "lib"
      - run: yarn run lint:ci
        working-directory: "lib"
      - run: yarn run format:check
        working-directory: "lib"
      - name: Run Tests
        run: yarn run test
        working-directory: "lib"
      - name: Post to a Slack channel on failure
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        if: ${{ failure() && github.ref_name == 'main' }}
        with:
          channel-id: "C03L5KRE2E8"
          payload: |
            {
              "text": "main branch failed for lib!"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
