name: Test infra

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches: [main]
    paths:
      - "tarpon/infra/**"
      - "tarpon/lib/**"
      - "lib/**"
  workflow_call:
jobs:
  test:
    name: test-infra
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Corepack enable
        run: corepack enable && yarn set version 4.0.2
      - name: Use Node.js 18x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "tarpon/yarn.lock"
      - run: yarn install --immutable
        working-directory: "tarpon"
      - run: yarn run synth:ci
        working-directory: "tarpon"
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      - name: Post to a Slack channel on failure
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        with:
          channel-id: "C03L5KRE2E8"
          payload: |
            {
              "text": "main branch failed for infra!"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
